[package]
name = "uhtml-pics-parse"
version = "0.2.0"
edition = "2021"
description = "UHTML图片批量提取工具 (Rust版本)"
authors = ["Claude"]

[dependencies]
clap = { version = "4.0", features = ["derive"] }
base64 = "0.21"
walkdir = "2.3"
anyhow = "1.0"
thiserror = "1.0"
image = "0.24"
